name: tut_spec
description: Built value types for tut.
version: 1.0.0
environment:
  sdk: '>=2.0.0-dev.54 <3.0.0'
dependencies:
  built_collection: ^4.0.0
  built_value: ^6.1.3
dev_dependencies:
  build_runner: ^0.10.2
  built_value_generator: ^6.1.3