name: tut_main
description: A new Flutter project.

environment:
  sdk: '>=2.0.0-dev.54 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  outline_material_icons: ^0.1.0
  
  gradient_widgets: ^0.3.0
  color: any
  sliver_glue:
    path: ../../sliver_glue
  transformer_page_view: ^0.1.4

  meta: "^1.1.5"
  intl: "^0.15.6"
  built_collection: ^4.0.0

  tut_spec:
    path: ../tut_spec
  tut_spec_mock:
    path: ../tut_spec_mock
  dartkit:
    path: ../dartkit
  telefrag:
    path: ../telefrag

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  fonts:
    - family: leaguespartan
      fonts:
        - asset: fonts/leaguespartan-bold.ttf
    - family: InterUI
      fonts:
        - asset: fonts/Inter-UI-Regular.ttf
        - asset: fonts/Inter-UI-Italic.ttf
          style: italic
        - asset: fonts/Inter-UI-Medium.ttf
          weight: 500
        - asset: fonts/Inter-UI-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Inter-UI-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter-UI-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/Inter-UI-Bold.ttf
          weight: 700
        - asset: fonts/Inter-UI-BoldItalic.ttf
          weight: 700
          style: italic